name: puzzle_ball_gklabs
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  audioplayers: ^6.1.0
  bloc: ^9.0.0
  equatable: ^2.0.5
  flame: ^1.20.0
  flame_audio: ^2.10.4
  flame_behaviors: ^1.2.0
  flame_forge2d: ^0.19.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  sensors_plus: ^6.1.1
  shared_preferences: ^2.5.3

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flame_test: ^1.17.1
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  mockingjay: ^1.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/images/components/
    - assets/images/parallax/
    - assets/licenses/poppins/

flutter_native_splash:
  # Usa una imagen de fondo completa que cubre todo (fondo + icono en uno)
  background_image: assets/images/splash_screen.png

  android_12:
    # Para Android 12+, debes seguir usando una imagen separada como ícono.
    # Sin embargo, como tu imagen es una única splash completa, puedes dejar esto vacío.
    # La imagen se verá algo recortada si la defines aquí, así que lo omitimos.
    # En cambio, dejamos solo el fondo.

    # Opcional: color de fondo para Android 12
    color: "#0b1627"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#0b1627"
    theme_color: "#0b1627"